### ISSUE TITLE
You can fly bikes and boats

### ISSUE THREAD

**Issue by Megamind42** [ToastinYou/ToastysCruiseControl#11]
Yeah.. Flying bikes and boats is a problem..

**Comment by ToastinYou** [comment]
fixed in v2.1.0

**Comment by JiminyKroket** [comment]
Not fixed for me and just updated. Fully deleted old file and restarted server
